cours/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.urls import path
from . import views

app_name = 'cours'

urlpatterns = [
    path('', views.GestionCoursListView.as_view(), name='gestion_liste_cours'),
    path('create/', views.CoursCreateView.as_view(), name='cours_create'),
    path('edit/<pk>/', views.CoursUpdateView.as_view(), name='cours_edit'),
    path('delete/<pk>/', views.CoursDeleteView.as_view(), name='cours_delete'),
    path('module/<pk>/', views.CoursModuleUpdateView.as_view(), name='cours_module_update'),
    path('module/<int:module_id>/contenu/<model_name>/create/',
        views.ContenuCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/contenu/<model_name>/<id>/',
        views.ContenuCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContenuDeleteView.as_view(),
        name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContenuListView.as_view(),
        name='module_content_liste'),

    path('matiere/<slug:matiere>/', views.CoursListView.as_view(),
        name='cours_liste_matiere'),
    path('detail/<slug:slug>/', views.CoursDetailView.as_view(), name='cours_detail'),
]

elearning/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.autodiscover()

from cours.views import CoursListView

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='connexion'),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        template_name='cours/cours/liste_cours.html'), name='deconnexion'),
    path('admin/', admin.site.urls),
    path('cours/', include('cours.urls', namespace='cours')),
    path('', CoursListView.as_view(), name='liste_cours'),
    path('etudiant/', include('etudiants.urls', namespace='etudiant')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cours/models.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

from .champs import ChampsPerso

# Create your models here.

class Matieres(models.Model):
    title = models.CharField('Matière du Cours', max_length=200, unique=True)
    slug = models.SlugField('URL', max_length=200, unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cours:cours_liste_matiere', args=[self.slug])


class Cours(models.Model):
    instructeur = models.ForeignKey(User, on_delete=models.CASCADE)
    etudiants = models.ManyToManyField(User, related_name='rejoindre_cours', blank=True)
    matiere = models.ForeignKey(Matieres, related_name='cours', on_delete=models.CASCADE)
    title = models.CharField('Titre du Cours', max_length=200)
    slug = models.SlugField('URL', max_length=200, unique=True)
    resume = models.TextField()
    date_de_creation = models.DateField('Date de création du Cours', auto_now_add=True)

    class Meta:
        ordering = ['-date_de_creation']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cours:cours_detail', args=[self.slug])

    def get_edit_url(self):
        return reverse('cours:cours_edit', args=[self.id])

    def get_delete_url(self):
        return reverse('cours:cours_delete', args=[self.id])

    def get_update_url(self):
        return reverse('cours:cours_module_update', args=[self.id])


class Modules(models.Model):
    cours = models.ForeignKey(Cours, related_name='modules', on_delete=models.CASCADE)
    title = models.CharField('Titre du Module', max_length=200)
    description = models.TextField('Description du Cours', blank=True)
    ordre = ChampsPerso(blank=True, for_fields=['cours'])

    class Meta:
        ordering = ['ordre']

    def __str__(self):
        return '{}. {}'.format(self.ordre, self.title)

    def get_absolute_url(self):
        return reverse('cours:module_content_liste', args=[self.id])


class Contenus(models.Model):
    module = models.ForeignKey(Modules, related_name='contenus', on_delete=models.CASCADE)
    content_types = models.ForeignKey(ContentType, on_delete=models.CASCADE,
        limit_choices_to={
            'model__in':(
                'text',
                'video',
                'image',
                'file'
            )
        }
    )
    identifiant = models.PositiveIntegerField()
    item = GenericForeignKey('content_types', 'identifiant')
    ordre = ChampsPerso(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['ordre']


class TypeContenu(models.Model):
    instructeur = models.ForeignKey(User, related_name='%(class)s_related', on_delete=models.CASCADE)
    title = models.CharField('Titre du contenu', max_length=250)
    date_de_creation = models.DateTimeField('Date de création', auto_now_add=True)
    date_mise_a_jour = models.DateTimeField('Date de mise en ligne', auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string('cours/contenu/{}.html'.format(
            self._meta.model_name), {'item': self})


class Text(TypeContenu):
    contenu = models.TextField('Description du contenu')


class File(TypeContenu):
    file = models.FileField('Ajouter un fichier', upload_to='fichier')


class Image(TypeContenu):
    file = models.FileField('Ajouter une image', upload_to='images')


class Video(TypeContenu):
    url = models.URLField("Ajouter l'url de la video")

cours/forms.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'

from django import forms
from django.forms.models import inlineformset_factory

from .models import Cours, Modules

ModuleFormSet = inlineformset_factory(
        Cours, Modules,
        fields=['title', 'description'],
        extra = 2, can_delete = True
    )

cours/views.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'

from django.apps import apps
from django.db.models import Count
from django.core.cache import cache
from django.urls import reverse_lazy
from django.forms.models import modelform_factory
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .forms import ModuleFormSet
from etudiants.forms import CoursEnrollementForm
from .models import Matieres, Cours, Modules, Contenus

# Create your views here.

class InstructeurMixin(object):
    def get_queryset(self):
        queryset = super(InstructeurMixin, self).get_queryset()
        return queryset.filter(instructeur=self.request.user)


class InstructeurEditMixin(object):
    def form_valid(self, form):
        form.instance.instructeur= self.request.user
        return super(InstructeurEditMixin, self).form_valid(form)


class InstructeurCoursMixin(InstructeurMixin, LoginRequiredMixin):
    model = Cours
    fields = ['matiere', 'title', 'slug', 'resume']
    success_url = reverse_lazy('cours:gestion_liste_cours')


class InstructeurCoursEditMixin(InstructeurCoursMixin, InstructeurEditMixin):
    fields = ['matiere', 'title', 'slug', 'resume']
    success_url = reverse_lazy('cours:gestion_liste_cours')
    template_name = 'cours/gestion/cours/formulaire_cours.html'


class GestionCoursListView(InstructeurCoursMixin, ListView):
    template_name = 'cours/gestion/cours/liste_cours.html'


class CoursCreateView(PermissionRequiredMixin, InstructeurCoursEditMixin, CreateView):
    permission_required = 'cours.add_cours'


class CoursUpdateView(PermissionRequiredMixin, InstructeurCoursEditMixin, UpdateView):
    permission_required = 'cours.change_cours'


class CoursDeleteView(PermissionRequiredMixin, InstructeurCoursMixin, DeleteView):
    template_name = 'cours/gestion/cours/supprimer_cours.html'
    success_url = reverse_lazy('cours:gestion_liste_cours')
    permission_required = 'cours.delete_cours'


class CoursModuleUpdateView(TemplateResponseMixin, View):
    template_name = 'cours/gestion/module/formulaire_module.html'
    cours = None

    def get_formset(self, data=None):
        return ModuleFormSet(instance=self.cours, prefix='module', data=data)

    def dispatch(self, request, pk):
        self.cours = get_object_or_404(Cours, id=pk, instructeur=request.user)
        return super(CoursModuleUpdateView, self).dispatch(request, pk)

    def get(self, request, *args, **kwargs):
        formset = self.get_formset()
        return self.render_to_response({'cours': self.cours, 'formset': formset})

    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('cours:gestion_liste_cours')

        return self.render_to_response({'cours': self.cours, 'formset':formset})


class ContenuCreateUpdateView(TemplateResponseMixin, View):
    module = model = obj = None
    template_name = 'cours/gestion/contenu/formulaire_contenu.html'

    def get_model(self, model_name):
        if model_name in ['text', 'video', 'image', 'file']:
            return apps.get_model(app_label='cours', model_name=model_name)
        return None

    def get_form(self, model, *args, **kwargs):
        Form = modelform_factory(model, exclude=[
            'instructeur', 'ordre',
            'date_de_creation', 'date_mise_a_jour'])
        return Form(*args, **kwargs)

    def dispatch(self, request, module_id, model_name, id=None):
        self.module = get_object_or_404(Modules, id=module_id,
            cours__instructeur=request.user)
        self.model = self.get_model(model_name)
        if id:
            self.obj = get_object_or_404(self.model, id=id, instructeur=request.user)
        return super(ContenuCreateUpdateView, self).dispatch(request, module_id, model_name, id)

    def get(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form, 'object': self.obj})

    def post(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj, data=request.POST, files=request.FILES)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.instructeur = request.user
            obj.save()

            if not id:
                Contenus.objects.create(module=self.module, item=obj)
            return redirect('cours:module_content_liste', self.module.id)

        return self.render_to_response({'form': form, 'object': self.obj})


class ContenuDeleteView(View):
    def post(self, request, id):
        contenu = get_object_or_404(Contenus, id=id, module__cours__instructeur=request.user)
        module = contenu.module
        contenu.item.delete()
        contenu.delete()

        return redirect('cours:module_content_liste', module.id)


class ModuleContenuListView(TemplateResponseMixin, View):
    template_name = 'cours/gestion/module/liste_contenu.html'

    def get(self, request, module_id):
        module = get_object_or_404(Modules, id=module_id,
            cours__instructeur=request.user)

        return self.render_to_response({'module': module})


class CoursListView(TemplateResponseMixin, View):
    model = Cours
    template_name = 'cours/cours/liste_cours.html'

    def get(self, request, matiere=None):
        matieres = cache.get('all_matieres')
        if not matieres:
            matieres = Matieres.objects.annotate(total_cours=Count('cours'))
            cache.set('all_matieres', matieres)

        all_cours = Cours.objects.annotate(total_modules=Count('modules'))
        if matiere:
            matiere = get_object_or_404(Matieres, slug=matiere)
            key = 'matiere_{}_cours'.format(matiere.id)
            cours = cache.get(key)
            if not cours:
                cours = all_cours.filter(matiere=matiere)
                cache.set(key, cours)
        else:
            cours = cache.get('all_cours')
            if not cours:
                cours = all_cours
                cache.set('all_cours', cours)
        return self.render_to_response({'matieres': matieres, 'matiere': matiere,
            'cours': cours})


class CoursDetailView(DetailView):
    model = Cours
    template_name = 'cours/cours/detail_cours.html'

    def get_context_data(self, **kwargs):
        context = super(CoursDetailView, self).get_context_data(**kwargs)
        context['formulaire_enrollement'] = CoursEnrollementForm(initial={'cours': self.object})
        return context

cours/templates/cours/gestion/module/formulaire_module.html
{% extends "base.html" %}
{% block title %}Edit "{{ cours.title }}"{% endblock %}

{% block content %}
    <div class="popular_courses">
        <div class="container">
            <div class="row pb-3">
                <div class="col-lg-8 col-md-8">
                    <h3 class="font-italic text-muted mb-1 font-weight-bold">
                    Edit "{{ cours.title|safe|upper }}"</h3>
                    <hr class="my-4">
                    {% if formset.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                <p {% if forloop.last %} class="mb-0"{% endif %}>
                                    {{ error }}
                                </p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form action="." method="post">
                        {{ formset.management_form }}
                        {% for form in formset %}
                            <div class="mt-10">
                                <input type="text" id="{{ form.title.id_for_label }}" class="single-input" placeholder="Saisir le titre du module" name="{{ form.title.name }}" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Saisir le titre du module'" required>
                            </div>

                            <div class="form-group mt-10">
                                <textarea id="{{ form.description.id_for_label }}" class="form-control shadow-sm mb-10" rows="5" name="{{ form.description.name }}" placeholder="Saisir la description du module" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Saisir la description du module'" required=""></textarea>
                            </div>

                            {% if formset.can_delete %}
                                <div class="switch-wrap d-flex">
                                    <p class="mr-3">{{ form.DELETE.label }}</p>
                                    <div class="primary-checkbox">
                                        <input type="checkbox" id="{{ form.DELETE.id_for_label }}" name="{{ form.DELETE.name }}">
                                        <label for="{{ form.DELETE.id_for_label }}"></label>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}

                        {% csrf_token %}
                        <input type="submit" class="shadow-sm btn btn-sm btn-primary btn-block text-uppercase" value="Save modules">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cours/templates/cours/gestion/module/liste_contenu.html
{% extends "base.html" %}
{% load cours %}

{% block title %}
    Module {{ module.ordre|add:1 }}: {{ module.title }}
{% endblock %}

{% block content %}
    {% with cours=module.cours %}
        <h1>Course "{{ cours.title }}"</h1>

        <div class="contents">
            <h3>Modules</h3>
            <ul id="modules">
                {% for m in cours.modules.all %}
                    <li data-id="{{ m.id }}" {% if m == module %} class="selected"{% endif %}>
                        <a href="{% url "cours:module_content_liste" m.id %}">
                            <span>
                                Module <span class="order">{{ m.ordre|add:1 }}</span>
                            </span><br>{{ m.title }}
                        </a>
                    </li>
                {% empty %}
                    <li>No modules yet.</li>
                {% endfor %}
            </ul>
            <p><a href="{% url "cours:cours_module_update" cours.id %}">Edit modules</a></p>
        </div>

        <div class="module">
            <h2>Module {{ module.ordre|add:1 }}: {{ module.title }}</h2>
            <h3>Module contents:</h3>

            <div id="module-contents">
                {% for contenu in module.contenus.all %}
                    <div data-id="{{ contenu.id }}">
                        {% with item=contenu.item %}
                            <p>{{ item }} ({{ item|model_name }})</p>
                            <a href="{% url "cours:module_content_update" module.id item|model_name item.id %}">Edit</a>
                            <form action="{% url "cours:module_content_delete" contenu.id %}"method="post">
                                <input type="submit" value="Delete">
                                {% csrf_token %}
                            </form>
                        {% endwith %}
                    </div>
                {% empty %}
                    <p>This module has no contents yet.</p>
                {% endfor %}
            </div>

            <h3>Add new content:</h3>
            <ul class="content-types">
                <li><a href="{% url "cours:module_content_create" module.id "text" %}"> Text</a></li>
                <li><a href="{% url "cours:module_content_create" module.id "image" %}">Image</a></li>
                <li><a href="{% url "cours:module_content_create" module.id "video" %}">Video</a></li>
                <li><a href="{% url "cours:module_content_create" module.id "file" %}">File</a></li>
            </ul>
        </div>
    {% endwith %}
{% endblock content %}