cours/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.urls import path
from . import views

app_name = 'cours'

urlpatterns = [
    path('', views.GestionCoursListView.as_view(), name='gestion_liste_cours'),
    path('create/', views.CoursCreateView.as_view(), name='cours_create'),
    path('edit/<pk>/', views.CoursUpdateView.as_view(), name='cours_edit'),
    path('delete/<pk>/', views.CoursDeleteView.as_view(), name='cours_delete'),
    path('module/<pk>/', views.CoursModuleUpdateView.as_view(), name='cours_module_update'),
    path('module/<int:module_id>/contenu/<model_name>/create/',
        views.ContenuCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/contenu/<model_name>/<id>/',
        views.ContenuCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContenuDeleteView.as_view(),
        name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContenuListView.as_view(),
        name='module_content_liste'),

    path('matiere/<slug:matiere>/', views.CoursListView.as_view(),
        name='cours_liste_matiere'),
    path('detail/<slug:slug>/', views.CoursDetailView.as_view(), name='cours_detail'),
]

elearning/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.autodiscover()

from cours.views import CoursListView

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='connexion'),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        template_name='cours/cours/liste_cours.html'), name='deconnexion'),
    path('admin/', admin.site.urls),
    path('cours/', include('cours.urls', namespace='cours')),
    path('', CoursListView.as_view(), name='liste_cours'),
    path('etudiant/', include('etudiants.urls', namespace='etudiant')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etudiants/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views

app_name = 'etudiant'

urlpatterns = [
    path('register/', views.EtudiantRegistrationView.as_view(),
        name='etudiant_registration'),
    path('enrollement/', views.EtudiantEnrollementCoursView.as_view(),
        name='etudiant_enrollement_cours'),
    path('cours/', views.EtudiantCoursListView.as_view(),
        name='etudiant_liste_cours'),
    path('cours/<pk>/', cache_page(60*1)(views.EtudiantCoursDetailView.as_view()),
        name='etudiant_detail_cours'),
    path('cours/<pk>/<module_id>/', cache_page(60*1)(views.EtudiantCoursDetailView.as_view()),
        name='etudiant_detail_cours_module'),
]

etudiants/models.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.db import models

# Create your models here.

cours/forms.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'

from django import forms
from django.forms.models import inlineformset_factory

from .models import Cours, Modules

ModuleFormSet = inlineformset_factory(
        Cours, Modules,
        fields=['title', 'description'],
        extra = 2, can_delete = True
    )

etudiants/forms.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django import forms
from cours.models import Cours

class CoursEnrollementForm(forms.Form):
    cours = forms.ModelChoiceField(
        queryset=Cours.objects.all(), widget=forms.HiddenInput)

cours/views.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'

from django.apps import apps
from django.db.models import Count
from django.core.cache import cache
from django.urls import reverse_lazy
from django.forms.models import modelform_factory
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .forms import ModuleFormSet
from etudiants.forms import CoursEnrollementForm
from .models import Matieres, Cours, Modules, Contenus

# Create your views here.

class InstructeurMixin(object):
    def get_queryset(self):
        queryset = super(InstructeurMixin, self).get_queryset()
        return queryset.filter(instructeur=self.request.user)


class InstructeurEditMixin(object):
    def form_valid(self, form):
        form.instance.instructeur= self.request.user
        return super(InstructeurEditMixin, self).form_valid(form)


class InstructeurCoursMixin(InstructeurMixin, LoginRequiredMixin):
    model = Cours
    fields = ['matiere', 'title', 'slug', 'resume']
    success_url = reverse_lazy('cours:gestion_liste_cours')


class InstructeurCoursEditMixin(InstructeurCoursMixin, InstructeurEditMixin):
    fields = ['matiere', 'title', 'slug', 'resume']
    success_url = reverse_lazy('cours:gestion_liste_cours')
    template_name = 'cours/gestion/cours/formulaire_cours.html'


class GestionCoursListView(InstructeurCoursMixin, ListView):
    template_name = 'cours/gestion/cours/liste_cours.html'


class CoursCreateView(PermissionRequiredMixin, InstructeurCoursEditMixin, CreateView):
    permission_required = 'cours.add_cours'


class CoursUpdateView(PermissionRequiredMixin, InstructeurCoursEditMixin, UpdateView):
    permission_required = 'cours.change_cours'


class CoursDeleteView(PermissionRequiredMixin, InstructeurCoursMixin, DeleteView):
    template_name = 'cours/gestion/cours/supprimer_cours.html'
    success_url = reverse_lazy('cours:gestion_liste_cours')
    permission_required = 'cours.delete_cours'


class CoursModuleUpdateView(TemplateResponseMixin, View):
    template_name = 'cours/gestion/module/formulaire_module.html'
    cours = None

    def get_formset(self, data=None):
        return ModuleFormSet(instance=self.cours, prefix='module', data=data)

    def dispatch(self, request, pk):
        self.cours = get_object_or_404(Cours, id=pk, instructeur=request.user)
        return super(CoursModuleUpdateView, self).dispatch(request, pk)

    def get(self, request, *args, **kwargs):
        formset = self.get_formset()
        return self.render_to_response({'cours': self.cours, 'formset': formset})

    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            return redirect('cours:gestion_liste_cours')

        return self.render_to_response({'cours': self.cours, 'formset':formset})


class ContenuCreateUpdateView(TemplateResponseMixin, View):
    module = model = obj = None
    template_name = 'cours/gestion/contenu/formulaire_contenu.html'

    def get_model(self, model_name):
        if model_name in ['text', 'video', 'image', 'file']:
            return apps.get_model(app_label='cours', model_name=model_name)
        return None

    def get_form(self, model, *args, **kwargs):
        Form = modelform_factory(model, exclude=[
            'instructeur', 'ordre',
            'date_de_creation', 'date_mise_a_jour'])
        return Form(*args, **kwargs)

    def dispatch(self, request, module_id, model_name, id=None):
        self.module = get_object_or_404(Modules, id=module_id,
            cours__instructeur=request.user)
        self.model = self.get_model(model_name)
        if id:
            self.obj = get_object_or_404(self.model, id=id, instructeur=request.user)
        return super(ContenuCreateUpdateView, self).dispatch(request, module_id, model_name, id)

    def get(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form, 'object': self.obj})

    def post(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj, data=request.POST, files=request.FILES)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.instructeur = request.user
            obj.save()

            if not id:
                Contenus.objects.create(module=self.module, item=obj)
            return redirect('cours:module_content_liste', self.module.id)

        return self.render_to_response({'form': form, 'object': self.obj})


class ContenuDeleteView(View):
    def post(self, request, id):
        contenu = get_object_or_404(Contenus, id=id, module__cours__instructeur=request.user)
        module = contenu.module
        contenu.item.delete()
        contenu.delete()

        return redirect('cours:module_content_liste', module.id)


class ModuleContenuListView(TemplateResponseMixin, View):
    template_name = 'cours/gestion/module/liste_contenu.html'

    def get(self, request, module_id):
        module = get_object_or_404(Modules, id=module_id,
            cours__instructeur=request.user)

        return self.render_to_response({'module': module})


class CoursListView(TemplateResponseMixin, View):
    model = Cours
    template_name = 'cours/cours/liste_cours.html'

    def get(self, request, matiere=None):
        matieres = cache.get('all_matieres')
        if not matieres:
            matieres = Matieres.objects.annotate(total_cours=Count('cours'))
            cache.set('all_matieres', matieres)

        all_cours = Cours.objects.annotate(total_modules=Count('modules'))
        if matiere:
            matiere = get_object_or_404(Matieres, slug=matiere)
            key = 'matiere_{}_cours'.format(matiere.id)
            cours = cache.get(key)
            if not cours:
                cours = all_cours.filter(matiere=matiere)
                cache.set(key, cours)
        else:
            cours = cache.get('all_cours')
            if not cours:
                cours = all_cours
                cache.set('all_cours', cours)
        return self.render_to_response({'matieres': matieres, 'matiere': matiere,
            'cours': cours})


class CoursDetailView(DetailView):
    model = Cours
    template_name = 'cours/cours/detail_cours.html'

    def get_context_data(self, **kwargs):
        context = super(CoursDetailView, self).get_context_data(**kwargs)
        context['formulaire_enrollement'] = CoursEnrollementForm(initial={'cours': self.object})
        return context

etudiants/views.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView

from cours.models import Cours, Modules, Matieres
from .forms import CoursEnrollementForm


# Create your views here.


class EtudiantRegistrationView(CreateView):
    template_name = 'etudiants/etudiant/registration_etudiant.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('etudiant:etudiant_liste_cours')

    def form_valid(self, form):
        result = super(EtudiantRegistrationView, self).form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password1'])
        login(self.request, user)
        return result


class EtudiantEnrollementCoursView(LoginRequiredMixin, FormView):
    cours = None
    form_class = CoursEnrollementForm

    def form_valid(self, form):
        self.cours = form.cleaned_data['cours']
        self.cours.etudiants.add(self.request.user)
        return super(EtudiantEnrollementCoursView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('etudiant:etudiant_detail_cours', args=[self.cours.id])



# Vue permettent aux étudiants de lister les cours auxquels
# ils sont inscrits
class EtudiantCoursListView(LoginRequiredMixin, ListView):
    model = Cours
    template_name = 'etudiants/cours/etudiant_liste_cours.html'

    def get_queryset(self):
        queryset = super(EtudiantCoursListView, self).get_queryset()
        return queryset.filter(etudiants__in=[self.request.user])


class EtudiantCoursDetailView(DetailView):
    model = Cours
    template_name = 'etudiants/cours/etudiant_detail_cours.html'

    def get_queryset(self):
        queryset = super(EtudiantCoursDetailView, self).get_queryset()
        return queryset.filter(etudiants__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super(EtudiantCoursDetailView, self).get_context_data(**kwargs)
        # obtenir les objets du cours
        cours = self.get_object()
        # obtenir le module courant
        if 'module_id' in self.kwargs:
            context['module'] = cours.modules.get(id=self.kwargs['module_id'])
        else:
            # get all module
            context['module'] = cours.modules.all()
        return context

etudiants/templates/etudiants/cours/etudiant_detail_cours.html
{# Template permettant aux étudiants inscrits d'accéder au contenu d'un cours. #}

{% extends "base.html" %}
{% load static cache %}
{% get_static_prefix as STATIC_PREFIX %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
    <div class="my-1">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 py-4 text-center mx-auto">
                    <div>
                        <h2>Module of the course</h2>
                        <p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope. It’s exciting to think about setting up your own viewing station.</p>
                    </div>
                </div>
            </div>

            <div class="p-5 bg-white rounded shadow-sm mb-5">
                <ul class="nav nav-tabs nav-pills flex-column flex-sm-row text-center bg-light border-0 rounded-nav">
                    {% for m in object.modules.all %}
                        <li data-id="{{ m.id }}" class="nav-item flex-sm-fill">
                            <a href="{% url "etudiant:etudiant_detail_cours_module" object.id m.id %}" class="nav-link border-0 text-uppercase font-weight-bold {% if m == module %} active {% endif %}"> Module {{ m.ordre|add:1 }}
                            </a>
                        </li>
                        {% empty %}
                            <li class="nav-item flex-sm-fill">
                                <a class="nav-link border-0 text-uppercase font-weight-bold">No modules yet.</a>
                            </li>
                    {% endfor %}
                </ul>

                <div class="tab-content">
                    {% cache 10 module_contenus module %}
                        <div class="pt-2 show fade">
                            <h3>{{ module.title }}</h3>
                            {% for content in module.contenus.all %}
                                {% with item=content.item %}
                                    {{ item.render }}
                                {% endwith %}
                            {% endfor %}
                        </div>
                    {% endcache %}
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="main_title">
                        <h2>Our Instructors</h2>
                        <p>There is a moment in the life of any aspiring astronomer that it is time to buy that first telescope. It’s exciting to think about setting up your own viewing station.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- single-instructor -->
                <div class="col-lg-3 col-sm-6">
                    <div class="single_instructor">
                        <div class="author">
                            <img src="{{ STATIC_PREFIX }}img/instructors/ins1.jpg" alt="">
                        </div>
                        <div class="author_decs">
                            <h4>Ethel Davis</h4>
                            <p class="profession">Sr. Faculty Data Science</p>
                            <p>If you are looking at blank cassettes on the web, you may be very confused at the
                            difference in price.</p>
                            <div class="social_icons">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- single-instructor -->
                <div class="col-lg-3 col-sm-6">
                    <div class="single_instructor">
                        <div class="author">
                            <img src="{{ STATIC_PREFIX }}img/instructors/ins2.jpg" alt="">
                        </div>
                        <div class="author_decs">
                            <h4>Rodney Cooper</h4>
                            <p class="profession">Sr. Faculty Data Science</p>
                            <p>If you are looking at blank cassettes on the web, you may be very confused at the
                            difference in price.</p>
                            <div class="social_icons">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- single-instructor -->
                <div class="col-lg-3 col-sm-6">
                    <div class="single_instructor">
                        <div class="author">
                            <img src="{{ STATIC_PREFIX }}img/instructors/ins3.jpg" alt="">
                        </div>
                        <div class="author_decs">
                            <h4>Dane Walker</h4>
                            <p class="profession">Sr. Faculty Data Science</p>
                            <p>If you are looking at blank cassettes on the web, you may be very confused at the
                            difference in price.</p>
                            <div class="social_icons">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- single-instructor -->
                <div class="col-lg-3 col-sm-6">
                    <div class="single_instructor">
                        <div class="author">
                            <img src="{{ STATIC_PREFIX }}img/instructors/ins4.jpg" alt="">
                        </div>
                        <div class="author_decs">
                            <h4>Lena Keller</h4>
                            <p class="profession">Sr. Faculty Data Science</p>
                            <p>If you are looking at blank cassettes on the web, you may be very confused at the
                            difference in price.</p>
                            <div class="social_icons">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

etudiants/templates/etudiants/cours/etudiant_liste_cours.html
{# template qui affiche les cours auxquelles l'utilisateur s'est inscrit. #}

{% extends "base.html" %}
{% load cache %}
{% block title %}My courses{% endblock title %}


{% block content %}
    {% block banner_area %}
    {% endblock banner_area %}

    {% block popular_courses %}
        <div class="popular_courses">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 my-4">
                        <hr data-content="mes cours" class="hr-text font-weight-bold">
                    </div>
                    <!-- table liste cours -->
                    <div class="col-lg-12 p-3 rounded shadow-sm">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr class="bg-primary text-white">
                                        <th scope="col" class="border-0">
                                            <div class="p-1 px-3 text-uppercase">cours</div>
                                        </th>

                                        <th scope="col" class="border-0">
                                            <div class="p-1 px-3 text-uppercase">date d'inscription</div>
                                        </th>

                                        <th scope="col" class="border-0">
                                            <div class="p-1 px-3 text-uppercase">progression</div>
                                        </th>

                                        <th scope="col" class="border-0">
                                            <div class="p-1 px-3 text-uppercase">certificats</div>
                                        </th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for c in object_list %}
                                        <tr>
                                            <th scope="row" class="border-0">
                                                <div class="p-2">
                                                    <div class="ml-3 d-inline-block align-middle">
                                                    <h5 class="mb-0">
                                                        <a href="{% url "etudiant:etudiant_detail_cours" c.id %}" class="text-dark d-inline-block align-middle">{{ c.title|safe }}
                                                        </a>
                                                    </h5>
                                                  </div>
                                                </div>
                                            </th>
                                            <td class="border-0 align-middle"><strong>{{ c.date_de_creation|date}}</strong></td>
                                            <td class="border-0 align-middle text-center"><strong>3</strong></td>
                                            <td class="border-0 align-middle text-center"><a href="#" class="text-dark"><i class="fa fa-trash"></i></a></td>
                                        </tr>
                                    {% empty %}

                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="popular_courses">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 my-4">
                        <hr data-content="Derniers cours publiés " class="hr-text font-weight-bold">
                    </div>
                    {% for c in object_list %}
                        <div class="col-lg-3 col-md-6">
                            <div class="single_course">
                                <div class="course_head overlay">
                                    <img class="img-fluid w-100" src="{{ STATIC_PREFIX }}img/trainer1.jpg" alt="{{ c.title }}">
                                </div>
                                <div class="course_content">
                                    <h4>
                                        <a href="{% url "etudiant:etudiant_detail_cours" c.id %}">{{ c.title|safe }}</a>
                                    </h4>
                                    <p>{{ c.resume|truncatewords:20|safe }}</p>
                                    <div class="course_meta d-flex justify-content-between">
                                        <div>
                                            <span class="meta_info text-uppercase">
                                                <i class="fa fa-clock-o"></i>
                                                {{ c.date_de_creation|date:"M Y" }}
                                            </span>

                                            <span class="text-uppercase">
                                                <a class="small h5" href="{% url "etudiant:etudiant_detail_cours" c.id %}">access content</a>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                    <p>
                        You are not enrolled in any courses yet.
                        <a href="{% url "liste_cours" %}">Browse courses</a> to enroll in a course.
                    </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endblock popular_courses %}
{% endblock content %}