cours/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.urls import path
from . import views

app_name = 'cours'

urlpatterns = [
    path('', views.GestionCoursListView.as_view(), name='gestion_liste_cours'),
    path('create/', views.CoursCreateView.as_view(), name='cours_create'),
    path('edit/<pk>/', views.CoursUpdateView.as_view(), name='cours_edit'),
    path('delete/<pk>/', views.CoursDeleteView.as_view(), name='cours_delete'),
    path('module/<pk>/', views.CoursModuleUpdateView.as_view(), name='cours_module_update'),
    path('module/<int:module_id>/contenu/<model_name>/create/',
        views.ContenuCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/contenu/<model_name>/<id>/',
        views.ContenuCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContenuDeleteView.as_view(),
        name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContenuListView.as_view(),
        name='module_content_liste'),

    path('matiere/<slug:matiere>/', views.CoursListView.as_view(),
        name='cours_liste_matiere'),
    path('detail/<slug:slug>/', views.CoursDetailView.as_view(), name='cours_detail'),
]

elearning/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.autodiscover()

from cours.views import CoursListView

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='connexion'),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        template_name='cours/cours/liste_cours.html'), name='deconnexion'),
    path('admin/', admin.site.urls),
    path('cours/', include('cours.urls', namespace='cours')),
    path('', CoursListView.as_view(), name='liste_cours'),
    path('etudiant/', include('etudiants.urls', namespace='etudiant')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etudiants/urls.py
# -*- coding: utf-8 -*-

"""
__init__.py

Crée par Flavien-hugs - 2019/12/05/.
Copyright (c) 2019 unsta. All rights reserved.

"""
__author__ = 'Flavien-hugs <contact@unsta.ci>'
__version__= '0.0.1'
__copyright__ = '© 2019 unsta projet elearning'


from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views

app_name = 'etudiant'

urlpatterns = [
    path('register/', views.EtudiantRegistrationView.as_view(),
        name='etudiant_registration'),
    path('enrollement/', views.EtudiantEnrollementCoursView.as_view(),
        name='etudiant_enrollement_cours'),
    path('cours/', views.EtudiantCoursListView.as_view(),
        name='etudiant_liste_cours'),
    path('cours/<pk>/', cache_page(60*1)(views.EtudiantCoursDetailView.as_view()),
        name='etudiant_detail_cours'),
    path('cours/<pk>/<module_id>/', cache_page(60*1)(views.EtudiantCoursDetailView.as_view()),
        name='etudiant_detail_cours_module'),
]

templates/layout/footer.html
{% load static %}{% get_static_prefix as STATIC_PREFIX %}


    <footer class="footer-area bg-light section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 single-footer-widget">
                    <h4>Education</h4>
                    <ul>
                        <li><a href="#">L'entreprise</a></li>
                        <li><a href="#">Alternance</a></li>
                        <li><a href="#">Forum</a></li>
                        <li><a href="#">Blog</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 single-footer-widget">
                    <h4>Entreprises</h4>
                    <ul>
                        <li><a href="#">Jobs</a></li>
                        <li><a href="#">Business</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 single-footer-widget">
                    <h4>En plus</h4>
                    <ul>
                        <li><a href="#">Devenez mentor</a></li>
                        <li><a href="#">Aide et FAQ</a></li>
                        <li><a href="#">Conditions Générales d'Utilisation</a></li>
                        <li><a href="#">Politique de Protection des Données Personnelles</a></li>
                        <li><a href="#">Nous contacter</a></li>
                    </ul>
                </div>
            </div>
            <div class="row footer-bottom d-flex justify-content-between">
                <p class="col-lg-8 col-sm-12 footer-text m-0">Copyright &copy;<script>document.write(new Date().getFullYear());</script></p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                </div>
            </div>
        </div>
    </footer>

templates/layout/meta.html
        {% load static %}
        {% get_static_prefix as STATIC_PREFIX %}

        <!--[if IE 7]><html class="ie ie7"><![endif]-->
        <!--[if IE 8]><html class="ie ie8"><![endif]-->
        <!--[if IE 9]><html class="ie ie9"><![endif]-->

        <meta charset="UTF-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="description" content="Free HTML5 Website Template by freehtml5.co">
        <meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive">
        <meta name="author" content="freehtml5.co">

        <!-- Facebook and Twitter integration -->
        <meta property="og:title" content="">
        <meta property="og:image" content="">
        <meta property="og:url" content="">
        <meta property="og:site_name" content="">
        <meta property="og:description" content="">
        <meta name="twitter:title" content="">
        <meta name="twitter:image" content="">
        <meta name="twitter:url" content="">
        <meta name="twitter:card" content="">

        <!-- <link rel="manifest" href="site.webmanifest"> -->
        <link rel="shortcut icon" type="image/x-icon" href="{{ STATIC_PREFIX }}img/favicon.png">
        <!-- Place favicon.ico in the root directory -->
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/bootstrap.css">
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/font-awesome.min.css">
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}vendors/linericon/style.css">
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}vendors/owl-carousel/owl.carousel.min.css">
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}vendors/lightbox/simpleLightbox.css">
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}vendors/nice-select/css/nice-select.css">
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}vendors/animate-css/animate.css">
        <!-- main css -->
        <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/style.css">
        <!-- FOR IE9 below -->

        <!--[if lt IE 9]>
        <script src="js/respond.min.js"></script>
        <![endif]-->

        <!--[if IE 7]><body class="ie7 lt-ie8 lt-ie9 lt-ie10"><![endif]-->
        <!--[if IE 8]><body class="ie8 lt-ie9 lt-ie10"><![endif]-->
        <!--[if IE 9]><body class="ie9 lt-ie10"><![endif]-->

templates/layout/navigation.html
        {% load static %}{% get_static_prefix as STATIC_PREFIX %}

        {# header top bar #}
        <header class="header_area">
            <div class="header-top">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-6 col-sm-6 col-4 header-top-left">
                            <a href="tel:+225 51 571 396">
                                <span class="lnr lnr-phone"></span>
                                <span class="text">
                                    <span class="text">+225 51 571 396</span>
                                </span>
                            </a>
                            <a href="mailto:unsta@pm.me">
                                <span class="lnr lnr-envelope"></span>
                                <span class="text">
                                    <span class="text">unsta@pm.me</span>
                                </span>
                            </a>
                        </div>
                        <div class="col-lg-6 col-sm-6 col-8 header-top-right">
                            {% if not request.user.is_authenticated %}
                                <a class="text-uppercase" href="{% url "connexion" %}">se connecter</a>
                                <a class="text-uppercase" href="{% url "etudiant:etudiant_registration" %}">s'inscrire</a>
                            {% endif %}
                            <a class="text-uppercase" href="#">en savoir plus</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="main_menu">
                {% if request.user.is_authenticated %}
                    <div class="search_input" id="search_input_box">
                        <div class="container">
                            <form class="d-flex justify-content-between" method="" action="">
                                <input type="text" class="form-control" id="search_input" placeholder="Que souhaitez-vous apprendre ?">
                                <button type="submit" class="btn"></button>
                                <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
                            </form>
                        </div>
                    </div>
                {% endif %}

                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <a class="navbar-brand logo_h" href="/">
                            <img src="{{ STATIC_PREFIX }}img/logo.png" alt="{{ title }}">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                         aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                            <ul class="nav navbar-nav menu_nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link {% if cours == cours %}active{% endif %}" href="{% url "cours:gestion_liste_cours" %}">cours</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">edu. for Business</a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">Enseigner sur educ.</a>
                                </li>
                                {% if request.user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link search" id="search">
                                            <i class="lnr lnr-magnifier font-weight-bold"></i>
                                        </a>
                                    </li>

                                    <li class="nav-item avatar dropdown">
                                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <img src="{{ STATIC_PREFIX }}img/avatar.jpg" class="rounded-circle" alt="avatar image" height="35">
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-lg-right dropdown-secondary"
                                          aria-labelledby="navbarDropdownMenuLink">
                                            <span class="dropdown-item font-weight-bolder text-capitalize">
                                                <i class="fa fa-user mr-3"></i>{{ user.username }}
                                            </span>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item font-weight-bold" href="{% url "etudiant:etudiant_liste_cours" %}">
                                                <i class="fa fa-home mr-3"></i>Tableau de bord
                                            </a>
                                            <a class="dropdown-item font-weight-bold" href="#">
                                                <i class="fa fa-cog mr-3"></i>Mes paramètres
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item font-weight-bold" href="{% url "cours:gestion_liste_cours" %}">
                                                <i class="fa fa-book mr-3"></i>Mes cours
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item font-weight-bold" href="{% url "deconnexion" %}">
                                                <i class="fa fa-power-off mr-3"></i>
                                                Déconnexion
                                            </a>
                                        </ul>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </header>{# end header top bar #}

templates/layout/script.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<script src="{{ STATIC_PREFIX }}js/jquery-3.2.1.min.js"></script>
<script src="{{ STATIC_PREFIX }}js/popper.js"></script>
<script src="{{ STATIC_PREFIX }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_PREFIX }}js/stellar.js"></script>
<script src="{{ STATIC_PREFIX }}js/owl-carousel-thumb.min.js"></script>
<script src="{{ STATIC_PREFIX }}js/jquery.ajaxchimp.min.js"></script>
<script src="{{ STATIC_PREFIX }}js/countdown.js"></script>
<script src="{{ STATIC_PREFIX }}js/mail-script.js"></script>
<script src="{{ STATIC_PREFIX }}js/theme.js"></script>


<script src="{{ STATIC_PREFIX }}vendors/nice-select/js/jquery.nice-select.min.js"></script>
<script src="{{ STATIC_PREFIX }}vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="{{ STATIC_PREFIX }}vendors/counter-up/jquery.counterup.js"></script>

templates/layout/sidebar.html
{% load static %}{% get_static_prefix as STATIC_PREFIX %}

<div class="col-lg-4 right-contents">
    <ul>
        <li>
            <a class="justify-content-between d-flex" href="#">
                <p>Instructeur</p>
                <span class="or">{{ cours.instructeur|safe }}</span>
            </a>
        </li>
        <li>
            <a class="justify-content-between d-flex" href="#">
                <p>Matière </p>
                <span>{{ cours.matiere|upper }}</span>
            </a>
        </li>
        <li>
            <a class="justify-content-between d-flex" href="#">
                <p>Nombre de modules </p>
                <span>{{ cours.modules.count }}</span>
            </a>
        </li>
        <li>
            <a class="justify-content-between d-flex" href="#">
                <p>Date de mise en ligne </p>
                <span>{{ cours.date_de_creation }}</span>
            </a>
        </li>
    </ul>
    {% if request.user.is_authenticated %}
        <form action="{% url "etudiant:etudiant_enrollement_cours" %}" method="post">
            {{ formulaire_enrollement }}
            {% csrf_token %}
            <input type="submit" class="primary-btn text-uppercase enroll shadow-none" value="Enroll now">
        </form>
        {% else %}
            <a href="{% url "etudiant:etudiant_registration" %}" class="primary-btn text-uppercase enroll">Enroll the course</a>
    {% endif %}


    <h4 class="title">Reviews</h4>
    <div class="content">
        <div class="review-top row pt-40">
            <div class="col-lg-12">
                <h6 class="mb-15">Provide Your Rating</h6>
                <div class="d-flex flex-row reviews justify-content-between">
                    <span>Quality</span>
                    <div class="star">
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                    <span>Outstanding</span>
                </div>
                <div class="d-flex flex-row reviews justify-content-between">
                    <span>Puncuality</span>
                    <div class="star">
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                    <span>Outstanding</span>
                </div>
                <div class="d-flex flex-row reviews justify-content-between">
                    <span>Quality</span>
                    <div class="star">
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star checked"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </div>
                    <span>Outstanding</span>
                </div>
            </div>
        </div>
        <div class="feedeback">
            <h6>Your Feedback</h6>
            <textarea name="feedback" class="form-control" cols="10" rows="10"></textarea>
            <div class="mt-10 text-right">
                <a href="#" class="primary-btn text-right text-uppercase shadow-none">Submit</a>
            </div>
        </div>
    </div>
</div>